### PR TITLE
feat: Gas optimisation solutions

### PR DESCRIPTION
**Pull request by rackstar**
## Overview

* Current deployment gas cost is 336001

### CODE REVIEW

**Comment by AsyaMaior** [comment]
> error InvalidTier

Hello!
define error like this syntax: 

`error InvalidTier();`

and in function: 
  
`        if (_tier >= 255) {
            revert InvalidTier(); 
        }
`

**Comment by AsyaMaior** [comment]
> > error InvalidTier
> 
> Hello! define error like this syntax:
> 
> `error InvalidTier();`
> 
> and in function:
> 
> ` if (_tier >= 255) { revert InvalidTier(); }`

I add custom errors to branch "stacey": https://github.com/rackstar/GasOptimisationFoundry/tree/stacey 

So, deployment cost: 376418

**Review by AsyaMaior — COMMENTED** [review]
Great job! I add info in comments

**Comment by rackstar** [comment]
> > error InvalidTier
> 
> Hello! define error like this syntax:
> 
> `error InvalidTier();`
> 
> and in function:
> 
> ` if (_tier >= 255) { revert InvalidTier(); }`

haha. i feel silly now! Thanks for fixing it. We're on 376418 now.

I'll merge your branch to this branch.

**Comment by ichikawa-itbook** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
glambertation, @hazelement, @hyangchun, @shu-yu, @truechuan, @colindog, @HallCheng, @SuperSine, @tsymiar, @arduino2018, @muktarpat, @devynnpalmer, @sirius65535, @fujiwaraizuho, @shiLinQing407, @shaswata56, @thanhnamit, @humblefool01, @ssivachidambaram, @Wang-Kai, @wyz210052253, @GavinNovate, @zag2017, @WongCM, @qiuquanwu, @erasmosoares, @beerhall, @ducthu, @0x73-w1337, @intrenet, @TRYtoBest, @BabyPichu1508, @dmitry-morgachev, @fooock, @citizen010, @baolintian, @moremanu, @benji09, @rkgreen, @KnicksKnacks, @vincentbdb, @korokd, @Zirpon, @mseminatore, @jxyzmahuan, @cryptoinformator-com, @mrnonz, @hardyscc, @Durairaj, @Sophrinix

**Pull request merged**
